[fuchsia] Use root-ssl-certificates in v2 runner manifests (#36703)
* Add a `use` for the `root-ssl-certificates` to ensure BoringSSL
  can read the certificates at /config/ssl
* Reformat manifest with `cmc format`

Fixes `HandshakeException`s when establishing a secure connection:

```
HandshakeException: Handshake error in client (OS Error:
        CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:393))
<asynchronous suspension>
```

Depends on changes that offer this directory to the runners,
e.g. https://fxrev.dev/737597

Bug: https://fxbug.dev/111712